/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AboutRouteImport } from './routes/about'
import { Route as ContactRouteImport } from './routes/contact'
import { Route as PricingRouteImport } from './routes/pricing'
import { Route as PrivacyPolicyRouteImport } from './routes/privacy-policy'
import { Route as TermsOfServiceRouteImport } from './routes/terms-of-service'
import { Route as AiSeoIndexRouteImport } from './routes/ai-seo/index'
import { Route as AiSeoAiCitationsMentionsRouteImport } from './routes/ai-seo/ai-citations-mentions'
import { Route as AiSeoAiOverviewsRouteImport } from './routes/ai-seo/ai-overviews'
import { Route as AiSeoAiRetrievalSystemsRouteImport } from './routes/ai-seo/ai-retrieval-systems'
import { Route as AiSeoAiVisibilityRouteImport } from './routes/ai-seo/ai-visibility'
import { Route as AiSeoAnswerEngineOptimizationRouteImport } from './routes/ai-seo/answer-engine-optimization'
import { Route as AiSeoGeoSeoRouteImport } from './routes/ai-seo/geo-seo'
import { Route as AiSeoLlmSeoRouteImport } from './routes/ai-seo/llm-seo'
import { Route as AiSeoLlmoRouteImport } from './routes/ai-seo/llmo'
import { Route as ContentMarketingIndexRouteImport } from './routes/content-marketing/index'
import { Route as ContentMarketingBloggingCopywritingRouteImport } from './routes/content-marketing/blogging-copywriting'
import { Route as ContentMarketingGuestPostingLinkBuildingRouteImport } from './routes/content-marketing/guest-posting-link-building'
import { Route as IndustriesIndexRouteImport } from './routes/industries/index'
import { Route as IndustriesSlugRouteImport } from './routes/industries/$slug'
import { Route as LocationsIndexRouteImport } from './routes/locations/index'
import { Route as LocationsSlugRouteImport } from './routes/locations/$slug'
import { Route as PaidAdvertisingIndexRouteImport } from './routes/paid-advertising/index'
import { Route as PaidAdvertisingGoogleAdsRouteImport } from './routes/paid-advertising/google-ads'
import { Route as PaidAdvertisingSocialMediaAdsRouteImport } from './routes/paid-advertising/social-media-ads'
import { Route as PaidAdvertisingSocialMediaMarketingRouteImport } from './routes/paid-advertising/social-media-marketing'
import { Route as SeoServicesIndexRouteImport } from './routes/seo-services/index'
import { Route as SeoServicesGeoTargetingSeoRouteImport } from './routes/seo-services/geo-targeting-seo'
import { Route as SeoServicesGlobalSeoRouteImport } from './routes/seo-services/global-seo'
import { Route as SeoServicesLocalCitationsGmbRouteImport } from './routes/seo-services/local-citations-gmb'
import { Route as SeoServicesLocalSeoRouteImport } from './routes/seo-services/local-seo'
import { Route as SeoServicesTechnicalSeoRouteImport } from './routes/seo-services/technical-seo'
import { Route as WebDesignDevelopmentIndexRouteImport } from './routes/web-design-development/index'
import { Route as WebDesignDevelopmentEcommerceDevelopmentRouteImport } from './routes/web-design-development/ecommerce-development'
import { Route as WebDesignDevelopmentWordpressDevelopmentRouteImport } from './routes/web-design-development/wordpress-development'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactRoute = ContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => rootRouteImport,
} as any)
const PricingRoute = PricingRouteImport.update({
  id: '/pricing',
  path: '/pricing',
  getParentRoute: () => rootRouteImport,
} as any)
const PrivacyPolicyRoute = PrivacyPolicyRouteImport.update({
  id: '/privacy-policy',
  path: '/privacy-policy',
  getParentRoute: () => rootRouteImport,
} as any)
const TermsOfServiceRoute = TermsOfServiceRouteImport.update({
  id: '/terms-of-service',
  path: '/terms-of-service',
  getParentRoute: () => rootRouteImport,
} as any)
const AiSeoIndexRoute = AiSeoIndexRouteImport.update({
  id: '/ai-seo/',
  path: '/ai-seo/',
  getParentRoute: () => rootRouteImport,
} as any)
const AiSeoAiCitationsMentionsRoute =
  AiSeoAiCitationsMentionsRouteImport.update({
    id: '/ai-seo/ai-citations-mentions',
    path: '/ai-seo/ai-citations-mentions',
    getParentRoute: () => rootRouteImport,
  } as any)
const AiSeoAiOverviewsRoute = AiSeoAiOverviewsRouteImport.update({
  id: '/ai-seo/ai-overviews',
  path: '/ai-seo/ai-overviews',
  getParentRoute: () => rootRouteImport,
} as any)
const AiSeoAiRetrievalSystemsRoute = AiSeoAiRetrievalSystemsRouteImport.update({
  id: '/ai-seo/ai-retrieval-systems',
  path: '/ai-seo/ai-retrieval-systems',
  getParentRoute: () => rootRouteImport,
} as any)
const AiSeoAiVisibilityRoute = AiSeoAiVisibilityRouteImport.update({
  id: '/ai-seo/ai-visibility',
  path: '/ai-seo/ai-visibility',
  getParentRoute: () => rootRouteImport,
} as any)
const AiSeoAnswerEngineOptimizationRoute =
  AiSeoAnswerEngineOptimizationRouteImport.update({
    id: '/ai-seo/answer-engine-optimization',
    path: '/ai-seo/answer-engine-optimization',
    getParentRoute: () => rootRouteImport,
  } as any)
const AiSeoGeoSeoRoute = AiSeoGeoSeoRouteImport.update({
  id: '/ai-seo/geo-seo',
  path: '/ai-seo/geo-seo',
  getParentRoute: () => rootRouteImport,
} as any)
const AiSeoLlmSeoRoute = AiSeoLlmSeoRouteImport.update({
  id: '/ai-seo/llm-seo',
  path: '/ai-seo/llm-seo',
  getParentRoute: () => rootRouteImport,
} as any)
const AiSeoLlmoRoute = AiSeoLlmoRouteImport.update({
  id: '/ai-seo/llmo',
  path: '/ai-seo/llmo',
  getParentRoute: () => rootRouteImport,
} as any)
const ContentMarketingIndexRoute = ContentMarketingIndexRouteImport.update({
  id: '/content-marketing/',
  path: '/content-marketing/',
  getParentRoute: () => rootRouteImport,
} as any)
const ContentMarketingBloggingCopywritingRoute =
  ContentMarketingBloggingCopywritingRouteImport.update({
    id: '/content-marketing/blogging-copywriting',
    path: '/content-marketing/blogging-copywriting',
    getParentRoute: () => rootRouteImport,
  } as any)
const ContentMarketingGuestPostingLinkBuildingRoute =
  ContentMarketingGuestPostingLinkBuildingRouteImport.update({
    id: '/content-marketing/guest-posting-link-building',
    path: '/content-marketing/guest-posting-link-building',
    getParentRoute: () => rootRouteImport,
  } as any)
const IndustriesIndexRoute = IndustriesIndexRouteImport.update({
  id: '/industries/',
  path: '/industries/',
  getParentRoute: () => rootRouteImport,
} as any)
const IndustriesSlugRoute = IndustriesSlugRouteImport.update({
  id: '/industries/$slug',
  path: '/industries/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const LocationsIndexRoute = LocationsIndexRouteImport.update({
  id: '/locations/',
  path: '/locations/',
  getParentRoute: () => rootRouteImport,
} as any)
const LocationsSlugRoute = LocationsSlugRouteImport.update({
  id: '/locations/$slug',
  path: '/locations/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const PaidAdvertisingIndexRoute = PaidAdvertisingIndexRouteImport.update({
  id: '/paid-advertising/',
  path: '/paid-advertising/',
  getParentRoute: () => rootRouteImport,
} as any)
const PaidAdvertisingGoogleAdsRoute =
  PaidAdvertisingGoogleAdsRouteImport.update({
    id: '/paid-advertising/google-ads',
    path: '/paid-advertising/google-ads',
    getParentRoute: () => rootRouteImport,
  } as any)
const PaidAdvertisingSocialMediaAdsRoute =
  PaidAdvertisingSocialMediaAdsRouteImport.update({
    id: '/paid-advertising/social-media-ads',
    path: '/paid-advertising/social-media-ads',
    getParentRoute: () => rootRouteImport,
  } as any)
const PaidAdvertisingSocialMediaMarketingRoute =
  PaidAdvertisingSocialMediaMarketingRouteImport.update({
    id: '/paid-advertising/social-media-marketing',
    path: '/paid-advertising/social-media-marketing',
    getParentRoute: () => rootRouteImport,
  } as any)
const SeoServicesIndexRoute = SeoServicesIndexRouteImport.update({
  id: '/seo-services/',
  path: '/seo-services/',
  getParentRoute: () => rootRouteImport,
} as any)
const SeoServicesGeoTargetingSeoRoute =
  SeoServicesGeoTargetingSeoRouteImport.update({
    id: '/seo-services/geo-targeting-seo',
    path: '/seo-services/geo-targeting-seo',
    getParentRoute: () => rootRouteImport,
  } as any)
const SeoServicesGlobalSeoRoute = SeoServicesGlobalSeoRouteImport.update({
  id: '/seo-services/global-seo',
  path: '/seo-services/global-seo',
  getParentRoute: () => rootRouteImport,
} as any)
const SeoServicesLocalCitationsGmbRoute =
  SeoServicesLocalCitationsGmbRouteImport.update({
    id: '/seo-services/local-citations-gmb',
    path: '/seo-services/local-citations-gmb',
    getParentRoute: () => rootRouteImport,
  } as any)
const SeoServicesLocalSeoRoute = SeoServicesLocalSeoRouteImport.update({
  id: '/seo-services/local-seo',
  path: '/seo-services/local-seo',
  getParentRoute: () => rootRouteImport,
} as any)
const SeoServicesTechnicalSeoRoute = SeoServicesTechnicalSeoRouteImport.update({
  id: '/seo-services/technical-seo',
  path: '/seo-services/technical-seo',
  getParentRoute: () => rootRouteImport,
} as any)
const WebDesignDevelopmentIndexRoute =
  WebDesignDevelopmentIndexRouteImport.update({
    id: '/web-design-development/',
    path: '/web-design-development/',
    getParentRoute: () => rootRouteImport,
  } as any)
const WebDesignDevelopmentEcommerceDevelopmentRoute =
  WebDesignDevelopmentEcommerceDevelopmentRouteImport.update({
    id: '/web-design-development/ecommerce-development',
    path: '/web-design-development/ecommerce-development',
    getParentRoute: () => rootRouteImport,
  } as any)
const WebDesignDevelopmentWordpressDevelopmentRoute =
  WebDesignDevelopmentWordpressDevelopmentRouteImport.update({
    id: '/web-design-development/wordpress-development',
    path: '/web-design-development/wordpress-development',
    getParentRoute: () => rootRouteImport,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/contact': typeof ContactRoute
  '/pricing': typeof PricingRoute
  '/privacy-policy': typeof PrivacyPolicyRoute
  '/terms-of-service': typeof TermsOfServiceRoute
  '/ai-seo/ai-citations-mentions': typeof AiSeoAiCitationsMentionsRoute
  '/ai-seo/ai-overviews': typeof AiSeoAiOverviewsRoute
  '/ai-seo/ai-retrieval-systems': typeof AiSeoAiRetrievalSystemsRoute
  '/ai-seo/ai-visibility': typeof AiSeoAiVisibilityRoute
  '/ai-seo/answer-engine-optimization': typeof AiSeoAnswerEngineOptimizationRoute
  '/ai-seo/geo-seo': typeof AiSeoGeoSeoRoute
  '/ai-seo/llm-seo': typeof AiSeoLlmSeoRoute
  '/ai-seo/llmo': typeof AiSeoLlmoRoute
  '/content-marketing/blogging-copywriting': typeof ContentMarketingBloggingCopywritingRoute
  '/content-marketing/guest-posting-link-building': typeof ContentMarketingGuestPostingLinkBuildingRoute
  '/industries/$slug': typeof IndustriesSlugRoute
  '/locations/$slug': typeof LocationsSlugRoute
  '/paid-advertising/google-ads': typeof PaidAdvertisingGoogleAdsRoute
  '/paid-advertising/social-media-ads': typeof PaidAdvertisingSocialMediaAdsRoute
  '/paid-advertising/social-media-marketing': typeof PaidAdvertisingSocialMediaMarketingRoute
  '/seo-services/geo-targeting-seo': typeof SeoServicesGeoTargetingSeoRoute
  '/seo-services/global-seo': typeof SeoServicesGlobalSeoRoute
  '/seo-services/local-citations-gmb': typeof SeoServicesLocalCitationsGmbRoute
  '/seo-services/local-seo': typeof SeoServicesLocalSeoRoute
  '/seo-services/technical-seo': typeof SeoServicesTechnicalSeoRoute
  '/web-design-development/ecommerce-development': typeof WebDesignDevelopmentEcommerceDevelopmentRoute
  '/web-design-development/wordpress-development': typeof WebDesignDevelopmentWordpressDevelopmentRoute
  '/ai-seo/': typeof AiSeoIndexRoute
  '/content-marketing/': typeof ContentMarketingIndexRoute
  '/industries/': typeof IndustriesIndexRoute
  '/locations/': typeof LocationsIndexRoute
  '/paid-advertising/': typeof PaidAdvertisingIndexRoute
  '/seo-services/': typeof SeoServicesIndexRoute
  '/web-design-development/': typeof WebDesignDevelopmentIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/contact': typeof ContactRoute
  '/pricing': typeof PricingRoute
  '/privacy-policy': typeof PrivacyPolicyRoute
  '/terms-of-service': typeof TermsOfServiceRoute
  '/ai-seo/ai-citations-mentions': typeof AiSeoAiCitationsMentionsRoute
  '/ai-seo/ai-overviews': typeof AiSeoAiOverviewsRoute
  '/ai-seo/ai-retrieval-systems': typeof AiSeoAiRetrievalSystemsRoute
  '/ai-seo/ai-visibility': typeof AiSeoAiVisibilityRoute
  '/ai-seo/answer-engine-optimization': typeof AiSeoAnswerEngineOptimizationRoute
  '/ai-seo/geo-seo': typeof AiSeoGeoSeoRoute
  '/ai-seo/llm-seo': typeof AiSeoLlmSeoRoute
  '/ai-seo/llmo': typeof AiSeoLlmoRoute
  '/content-marketing/blogging-copywriting': typeof ContentMarketingBloggingCopywritingRoute
  '/content-marketing/guest-posting-link-building': typeof ContentMarketingGuestPostingLinkBuildingRoute
  '/industries/$slug': typeof IndustriesSlugRoute
  '/locations/$slug': typeof LocationsSlugRoute
  '/paid-advertising/google-ads': typeof PaidAdvertisingGoogleAdsRoute
  '/paid-advertising/social-media-ads': typeof PaidAdvertisingSocialMediaAdsRoute
  '/paid-advertising/social-media-marketing': typeof PaidAdvertisingSocialMediaMarketingRoute
  '/seo-services/geo-targeting-seo': typeof SeoServicesGeoTargetingSeoRoute
  '/seo-services/global-seo': typeof SeoServicesGlobalSeoRoute
  '/seo-services/local-citations-gmb': typeof SeoServicesLocalCitationsGmbRoute
  '/seo-services/local-seo': typeof SeoServicesLocalSeoRoute
  '/seo-services/technical-seo': typeof SeoServicesTechnicalSeoRoute
  '/web-design-development/ecommerce-development': typeof WebDesignDevelopmentEcommerceDevelopmentRoute
  '/web-design-development/wordpress-development': typeof WebDesignDevelopmentWordpressDevelopmentRoute
  '/ai-seo': typeof AiSeoIndexRoute
  '/content-marketing': typeof ContentMarketingIndexRoute
  '/industries': typeof IndustriesIndexRoute
  '/locations': typeof LocationsIndexRoute
  '/paid-advertising': typeof PaidAdvertisingIndexRoute
  '/seo-services': typeof SeoServicesIndexRoute
  '/web-design-development': typeof WebDesignDevelopmentIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/contact': typeof ContactRoute
  '/pricing': typeof PricingRoute
  '/privacy-policy': typeof PrivacyPolicyRoute
  '/terms-of-service': typeof TermsOfServiceRoute
  '/ai-seo/ai-citations-mentions': typeof AiSeoAiCitationsMentionsRoute
  '/ai-seo/ai-overviews': typeof AiSeoAiOverviewsRoute
  '/ai-seo/ai-retrieval-systems': typeof AiSeoAiRetrievalSystemsRoute
  '/ai-seo/ai-visibility': typeof AiSeoAiVisibilityRoute
  '/ai-seo/answer-engine-optimization': typeof AiSeoAnswerEngineOptimizationRoute
  '/ai-seo/geo-seo': typeof AiSeoGeoSeoRoute
  '/ai-seo/llm-seo': typeof AiSeoLlmSeoRoute
  '/ai-seo/llmo': typeof AiSeoLlmoRoute
  '/content-marketing/blogging-copywriting': typeof ContentMarketingBloggingCopywritingRoute
  '/content-marketing/guest-posting-link-building': typeof ContentMarketingGuestPostingLinkBuildingRoute
  '/industries/$slug': typeof IndustriesSlugRoute
  '/locations/$slug': typeof LocationsSlugRoute
  '/paid-advertising/google-ads': typeof PaidAdvertisingGoogleAdsRoute
  '/paid-advertising/social-media-ads': typeof PaidAdvertisingSocialMediaAdsRoute
  '/paid-advertising/social-media-marketing': typeof PaidAdvertisingSocialMediaMarketingRoute
  '/seo-services/geo-targeting-seo': typeof SeoServicesGeoTargetingSeoRoute
  '/seo-services/global-seo': typeof SeoServicesGlobalSeoRoute
  '/seo-services/local-citations-gmb': typeof SeoServicesLocalCitationsGmbRoute
  '/seo-services/local-seo': typeof SeoServicesLocalSeoRoute
  '/seo-services/technical-seo': typeof SeoServicesTechnicalSeoRoute
  '/web-design-development/ecommerce-development': typeof WebDesignDevelopmentEcommerceDevelopmentRoute
  '/web-design-development/wordpress-development': typeof WebDesignDevelopmentWordpressDevelopmentRoute
  '/ai-seo/': typeof AiSeoIndexRoute
  '/content-marketing/': typeof ContentMarketingIndexRoute
  '/industries/': typeof IndustriesIndexRoute
  '/locations/': typeof LocationsIndexRoute
  '/paid-advertising/': typeof PaidAdvertisingIndexRoute
  '/seo-services/': typeof SeoServicesIndexRoute
  '/web-design-development/': typeof WebDesignDevelopmentIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/contact'
    | '/pricing'
    | '/privacy-policy'
    | '/terms-of-service'
    | '/ai-seo/ai-citations-mentions'
    | '/ai-seo/ai-overviews'
    | '/ai-seo/ai-retrieval-systems'
    | '/ai-seo/ai-visibility'
    | '/ai-seo/answer-engine-optimization'
    | '/ai-seo/geo-seo'
    | '/ai-seo/llm-seo'
    | '/ai-seo/llmo'
    | '/content-marketing/blogging-copywriting'
    | '/content-marketing/guest-posting-link-building'
    | '/industries/$slug'
    | '/locations/$slug'
    | '/paid-advertising/google-ads'
    | '/paid-advertising/social-media-ads'
    | '/paid-advertising/social-media-marketing'
    | '/seo-services/geo-targeting-seo'
    | '/seo-services/global-seo'
    | '/seo-services/local-citations-gmb'
    | '/seo-services/local-seo'
    | '/seo-services/technical-seo'
    | '/web-design-development/ecommerce-development'
    | '/web-design-development/wordpress-development'
    | '/ai-seo/'
    | '/content-marketing/'
    | '/industries/'
    | '/locations/'
    | '/paid-advertising/'
    | '/seo-services/'
    | '/web-design-development/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/contact'
    | '/pricing'
    | '/privacy-policy'
    | '/terms-of-service'
    | '/ai-seo/ai-citations-mentions'
    | '/ai-seo/ai-overviews'
    | '/ai-seo/ai-retrieval-systems'
    | '/ai-seo/ai-visibility'
    | '/ai-seo/answer-engine-optimization'
    | '/ai-seo/geo-seo'
    | '/ai-seo/llm-seo'
    | '/ai-seo/llmo'
    | '/content-marketing/blogging-copywriting'
    | '/content-marketing/guest-posting-link-building'
    | '/industries/$slug'
    | '/locations/$slug'
    | '/paid-advertising/google-ads'
    | '/paid-advertising/social-media-ads'
    | '/paid-advertising/social-media-marketing'
    | '/seo-services/geo-targeting-seo'
    | '/seo-services/global-seo'
    | '/seo-services/local-citations-gmb'
    | '/seo-services/local-seo'
    | '/seo-services/technical-seo'
    | '/web-design-development/ecommerce-development'
    | '/web-design-development/wordpress-development'
    | '/ai-seo'
    | '/content-marketing'
    | '/industries'
    | '/locations'
    | '/paid-advertising'
    | '/seo-services'
    | '/web-design-development'
  id:
    | '__root__'
    | '/'
    | '/about'
    | '/contact'
    | '/pricing'
    | '/privacy-policy'
    | '/terms-of-service'
    | '/ai-seo/ai-citations-mentions'
    | '/ai-seo/ai-overviews'
    | '/ai-seo/ai-retrieval-systems'
    | '/ai-seo/ai-visibility'
    | '/ai-seo/answer-engine-optimization'
    | '/ai-seo/geo-seo'
    | '/ai-seo/llm-seo'
    | '/ai-seo/llmo'
    | '/content-marketing/blogging-copywriting'
    | '/content-marketing/guest-posting-link-building'
    | '/industries/$slug'
    | '/locations/$slug'
    | '/paid-advertising/google-ads'
    | '/paid-advertising/social-media-ads'
    | '/paid-advertising/social-media-marketing'
    | '/seo-services/geo-targeting-seo'
    | '/seo-services/global-seo'
    | '/seo-services/local-citations-gmb'
    | '/seo-services/local-seo'
    | '/seo-services/technical-seo'
    | '/web-design-development/ecommerce-development'
    | '/web-design-development/wordpress-development'
    | '/ai-seo/'
    | '/content-marketing/'
    | '/industries/'
    | '/locations/'
    | '/paid-advertising/'
    | '/seo-services/'
    | '/web-design-development/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AboutRoute: typeof AboutRoute
  ContactRoute: typeof ContactRoute
  PricingRoute: typeof PricingRoute
  PrivacyPolicyRoute: typeof PrivacyPolicyRoute
  TermsOfServiceRoute: typeof TermsOfServiceRoute
  AiSeoAiCitationsMentionsRoute: typeof AiSeoAiCitationsMentionsRoute
  AiSeoAiOverviewsRoute: typeof AiSeoAiOverviewsRoute
  AiSeoAiRetrievalSystemsRoute: typeof AiSeoAiRetrievalSystemsRoute
  AiSeoAiVisibilityRoute: typeof AiSeoAiVisibilityRoute
  AiSeoAnswerEngineOptimizationRoute: typeof AiSeoAnswerEngineOptimizationRoute
  AiSeoGeoSeoRoute: typeof AiSeoGeoSeoRoute
  AiSeoLlmSeoRoute: typeof AiSeoLlmSeoRoute
  AiSeoLlmoRoute: typeof AiSeoLlmoRoute
  ContentMarketingBloggingCopywritingRoute: typeof ContentMarketingBloggingCopywritingRoute
  ContentMarketingGuestPostingLinkBuildingRoute: typeof ContentMarketingGuestPostingLinkBuildingRoute
  IndustriesSlugRoute: typeof IndustriesSlugRoute
  LocationsSlugRoute: typeof LocationsSlugRoute
  PaidAdvertisingGoogleAdsRoute: typeof PaidAdvertisingGoogleAdsRoute
  PaidAdvertisingSocialMediaAdsRoute: typeof PaidAdvertisingSocialMediaAdsRoute
  PaidAdvertisingSocialMediaMarketingRoute: typeof PaidAdvertisingSocialMediaMarketingRoute
  SeoServicesGeoTargetingSeoRoute: typeof SeoServicesGeoTargetingSeoRoute
  SeoServicesGlobalSeoRoute: typeof SeoServicesGlobalSeoRoute
  SeoServicesLocalCitationsGmbRoute: typeof SeoServicesLocalCitationsGmbRoute
  SeoServicesLocalSeoRoute: typeof SeoServicesLocalSeoRoute
  SeoServicesTechnicalSeoRoute: typeof SeoServicesTechnicalSeoRoute
  WebDesignDevelopmentEcommerceDevelopmentRoute: typeof WebDesignDevelopmentEcommerceDevelopmentRoute
  WebDesignDevelopmentWordpressDevelopmentRoute: typeof WebDesignDevelopmentWordpressDevelopmentRoute
  AiSeoIndexRoute: typeof AiSeoIndexRoute
  ContentMarketingIndexRoute: typeof ContentMarketingIndexRoute
  IndustriesIndexRoute: typeof IndustriesIndexRoute
  LocationsIndexRoute: typeof LocationsIndexRoute
  PaidAdvertisingIndexRoute: typeof PaidAdvertisingIndexRoute
  SeoServicesIndexRoute: typeof SeoServicesIndexRoute
  WebDesignDevelopmentIndexRoute: typeof WebDesignDevelopmentIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contact': {
      id: '/contact'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof ContactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pricing': {
      id: '/pricing'
      path: '/pricing'
      fullPath: '/pricing'
      preLoaderRoute: typeof PricingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/privacy-policy': {
      id: '/privacy-policy'
      path: '/privacy-policy'
      fullPath: '/privacy-policy'
      preLoaderRoute: typeof PrivacyPolicyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/terms-of-service': {
      id: '/terms-of-service'
      path: '/terms-of-service'
      fullPath: '/terms-of-service'
      preLoaderRoute: typeof TermsOfServiceRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ai-seo/': {
      id: '/ai-seo/'
      path: '/ai-seo'
      fullPath: '/ai-seo/'
      preLoaderRoute: typeof AiSeoIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ai-seo/ai-citations-mentions': {
      id: '/ai-seo/ai-citations-mentions'
      path: '/ai-seo/ai-citations-mentions'
      fullPath: '/ai-seo/ai-citations-mentions'
      preLoaderRoute: typeof AiSeoAiCitationsMentionsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ai-seo/ai-overviews': {
      id: '/ai-seo/ai-overviews'
      path: '/ai-seo/ai-overviews'
      fullPath: '/ai-seo/ai-overviews'
      preLoaderRoute: typeof AiSeoAiOverviewsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ai-seo/ai-retrieval-systems': {
      id: '/ai-seo/ai-retrieval-systems'
      path: '/ai-seo/ai-retrieval-systems'
      fullPath: '/ai-seo/ai-retrieval-systems'
      preLoaderRoute: typeof AiSeoAiRetrievalSystemsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ai-seo/ai-visibility': {
      id: '/ai-seo/ai-visibility'
      path: '/ai-seo/ai-visibility'
      fullPath: '/ai-seo/ai-visibility'
      preLoaderRoute: typeof AiSeoAiVisibilityRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ai-seo/answer-engine-optimization': {
      id: '/ai-seo/answer-engine-optimization'
      path: '/ai-seo/answer-engine-optimization'
      fullPath: '/ai-seo/answer-engine-optimization'
      preLoaderRoute: typeof AiSeoAnswerEngineOptimizationRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ai-seo/geo-seo': {
      id: '/ai-seo/geo-seo'
      path: '/ai-seo/geo-seo'
      fullPath: '/ai-seo/geo-seo'
      preLoaderRoute: typeof AiSeoGeoSeoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ai-seo/llm-seo': {
      id: '/ai-seo/llm-seo'
      path: '/ai-seo/llm-seo'
      fullPath: '/ai-seo/llm-seo'
      preLoaderRoute: typeof AiSeoLlmSeoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ai-seo/llmo': {
      id: '/ai-seo/llmo'
      path: '/ai-seo/llmo'
      fullPath: '/ai-seo/llmo'
      preLoaderRoute: typeof AiSeoLlmoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/content-marketing/': {
      id: '/content-marketing/'
      path: '/content-marketing'
      fullPath: '/content-marketing/'
      preLoaderRoute: typeof ContentMarketingIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/content-marketing/blogging-copywriting': {
      id: '/content-marketing/blogging-copywriting'
      path: '/content-marketing/blogging-copywriting'
      fullPath: '/content-marketing/blogging-copywriting'
      preLoaderRoute: typeof ContentMarketingBloggingCopywritingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/content-marketing/guest-posting-link-building': {
      id: '/content-marketing/guest-posting-link-building'
      path: '/content-marketing/guest-posting-link-building'
      fullPath: '/content-marketing/guest-posting-link-building'
      preLoaderRoute: typeof ContentMarketingGuestPostingLinkBuildingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/industries/': {
      id: '/industries/'
      path: '/industries'
      fullPath: '/industries/'
      preLoaderRoute: typeof IndustriesIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/industries/$slug': {
      id: '/industries/$slug'
      path: '/industries/$slug'
      fullPath: '/industries/$slug'
      preLoaderRoute: typeof IndustriesSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/locations/': {
      id: '/locations/'
      path: '/locations'
      fullPath: '/locations/'
      preLoaderRoute: typeof LocationsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/locations/$slug': {
      id: '/locations/$slug'
      path: '/locations/$slug'
      fullPath: '/locations/$slug'
      preLoaderRoute: typeof LocationsSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/paid-advertising/': {
      id: '/paid-advertising/'
      path: '/paid-advertising'
      fullPath: '/paid-advertising/'
      preLoaderRoute: typeof PaidAdvertisingIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/paid-advertising/google-ads': {
      id: '/paid-advertising/google-ads'
      path: '/paid-advertising/google-ads'
      fullPath: '/paid-advertising/google-ads'
      preLoaderRoute: typeof PaidAdvertisingGoogleAdsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/paid-advertising/social-media-ads': {
      id: '/paid-advertising/social-media-ads'
      path: '/paid-advertising/social-media-ads'
      fullPath: '/paid-advertising/social-media-ads'
      preLoaderRoute: typeof PaidAdvertisingSocialMediaAdsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/paid-advertising/social-media-marketing': {
      id: '/paid-advertising/social-media-marketing'
      path: '/paid-advertising/social-media-marketing'
      fullPath: '/paid-advertising/social-media-marketing'
      preLoaderRoute: typeof PaidAdvertisingSocialMediaMarketingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/seo-services/': {
      id: '/seo-services/'
      path: '/seo-services'
      fullPath: '/seo-services/'
      preLoaderRoute: typeof SeoServicesIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/seo-services/geo-targeting-seo': {
      id: '/seo-services/geo-targeting-seo'
      path: '/seo-services/geo-targeting-seo'
      fullPath: '/seo-services/geo-targeting-seo'
      preLoaderRoute: typeof SeoServicesGeoTargetingSeoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/seo-services/global-seo': {
      id: '/seo-services/global-seo'
      path: '/seo-services/global-seo'
      fullPath: '/seo-services/global-seo'
      preLoaderRoute: typeof SeoServicesGlobalSeoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/seo-services/local-citations-gmb': {
      id: '/seo-services/local-citations-gmb'
      path: '/seo-services/local-citations-gmb'
      fullPath: '/seo-services/local-citations-gmb'
      preLoaderRoute: typeof SeoServicesLocalCitationsGmbRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/seo-services/local-seo': {
      id: '/seo-services/local-seo'
      path: '/seo-services/local-seo'
      fullPath: '/seo-services/local-seo'
      preLoaderRoute: typeof SeoServicesLocalSeoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/seo-services/technical-seo': {
      id: '/seo-services/technical-seo'
      path: '/seo-services/technical-seo'
      fullPath: '/seo-services/technical-seo'
      preLoaderRoute: typeof SeoServicesTechnicalSeoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/web-design-development/': {
      id: '/web-design-development/'
      path: '/web-design-development'
      fullPath: '/web-design-development/'
      preLoaderRoute: typeof WebDesignDevelopmentIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/web-design-development/ecommerce-development': {
      id: '/web-design-development/ecommerce-development'
      path: '/web-design-development/ecommerce-development'
      fullPath: '/web-design-development/ecommerce-development'
      preLoaderRoute: typeof WebDesignDevelopmentEcommerceDevelopmentRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/web-design-development/wordpress-development': {
      id: '/web-design-development/wordpress-development'
      path: '/web-design-development/wordpress-development'
      fullPath: '/web-design-development/wordpress-development'
      preLoaderRoute: typeof WebDesignDevelopmentWordpressDevelopmentRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AboutRoute: AboutRoute,
  ContactRoute: ContactRoute,
  PricingRoute: PricingRoute,
  PrivacyPolicyRoute: PrivacyPolicyRoute,
  TermsOfServiceRoute: TermsOfServiceRoute,
  AiSeoAiCitationsMentionsRoute: AiSeoAiCitationsMentionsRoute,
  AiSeoAiOverviewsRoute: AiSeoAiOverviewsRoute,
  AiSeoAiRetrievalSystemsRoute: AiSeoAiRetrievalSystemsRoute,
  AiSeoAiVisibilityRoute: AiSeoAiVisibilityRoute,
  AiSeoAnswerEngineOptimizationRoute: AiSeoAnswerEngineOptimizationRoute,
  AiSeoGeoSeoRoute: AiSeoGeoSeoRoute,
  AiSeoLlmSeoRoute: AiSeoLlmSeoRoute,
  AiSeoLlmoRoute: AiSeoLlmoRoute,
  ContentMarketingBloggingCopywritingRoute:
    ContentMarketingBloggingCopywritingRoute,
  ContentMarketingGuestPostingLinkBuildingRoute:
    ContentMarketingGuestPostingLinkBuildingRoute,
  IndustriesSlugRoute: IndustriesSlugRoute,
  LocationsSlugRoute: LocationsSlugRoute,
  PaidAdvertisingGoogleAdsRoute: PaidAdvertisingGoogleAdsRoute,
  PaidAdvertisingSocialMediaAdsRoute: PaidAdvertisingSocialMediaAdsRoute,
  PaidAdvertisingSocialMediaMarketingRoute:
    PaidAdvertisingSocialMediaMarketingRoute,
  SeoServicesGeoTargetingSeoRoute: SeoServicesGeoTargetingSeoRoute,
  SeoServicesGlobalSeoRoute: SeoServicesGlobalSeoRoute,
  SeoServicesLocalCitationsGmbRoute: SeoServicesLocalCitationsGmbRoute,
  SeoServicesLocalSeoRoute: SeoServicesLocalSeoRoute,
  SeoServicesTechnicalSeoRoute: SeoServicesTechnicalSeoRoute,
  WebDesignDevelopmentEcommerceDevelopmentRoute:
    WebDesignDevelopmentEcommerceDevelopmentRoute,
  WebDesignDevelopmentWordpressDevelopmentRoute:
    WebDesignDevelopmentWordpressDevelopmentRoute,
  AiSeoIndexRoute: AiSeoIndexRoute,
  ContentMarketingIndexRoute: ContentMarketingIndexRoute,
  IndustriesIndexRoute: IndustriesIndexRoute,
  LocationsIndexRoute: LocationsIndexRoute,
  PaidAdvertisingIndexRoute: PaidAdvertisingIndexRoute,
  SeoServicesIndexRoute: SeoServicesIndexRoute,
  WebDesignDevelopmentIndexRoute: WebDesignDevelopmentIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
